[tool.poetry]
name = "profitpilotai"
version = "0.1.0"
description = "ProfitPilotAI - FastAPI backend with Supabase, Telegram Bot, and Deriv WebSocket"
authors = ["Your Name <your-email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.111.0"
uvicorn = "0.30.1"
supabase = "2.4.0"
python-dotenv = "1.0.1"
requests = "2.32.3"
httpx = "0.27.0"
aiohttp = "3.9.5"
pandas = "2.2.2"
numpy = "1.26.4"
python-telegram-bot = "21.4"
websockets = "12.0"
loguru = "0.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
