services:
  - type: web
    name: profitpilotai
    env: python
    plan: free
    branch: main
    region: oregon
    autoDeploy: true
    buildCommand: poetry install --no-root
    startCommand: poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
